### ISSUE TITLE
skin_head 모델의 torch→onnx 변환 과정에서 input layer 정보가 전달되지 않는 문제

### ISSUE THREAD

**Issue by lhy0718** [laymond1/yolov7-nas-for-TANGO#11]
- skin_head 모델의 torch→onnx 변환 과정에서 input layer 정보가 전달되지 않는 문제
- 문제에 따른 이슈
  - torch2tflite 변환 검증코드가 작동하지 않음
    ```
    ---------------------------------------------------------------------------
    IndexError                                Traceback (most recent call last)
    Cell In[42], line 29
         26 file_list = [d for d in os.listdir(out_dir) if d.endswith('pt') and d.startswith('head')]
         28 for torch_file in tqdm(file_list[:1]):
    ---> 29     arch2tflite(torch_file[:-3], out_dir)
         30     # os.remove(os.path.join(out_dir, torch_file))
    
    Cell In[42], line 19, in arch2tflite(name, out_dir)
         12     dummy_input_shape = (1, 1024, 20, 20)
         14 conv = Torch2TFLiteConverter(
         15     base_path + '.pt',
         16     base_path + '.tflite',
         17     target_shape = dummy_input_shape,
         18 )
    ---> 19 conv.convert(remove_tmp_dir=True)
    
    File [~/yolov7-nas-for-TANGO/torch2tflite/torch2tflite/converter.py:51](), in Torch2TFLiteConverter.convert(self, remove_tmp_dir)
         49 self.tf2tflite()
         50 torch_output = self.inference_torch()
    ---> 51 tflite_output = self.inference_tflite(self.load_tflite())
         52 self.calc_error(torch_output, tflite_output)
         54 if remove_tmp_dir:
    
    File [~/yolov7-nas-for-TANGO/torch2tflite/torch2tflite/converter.py:197](), in Torch2TFLiteConverter.inference_tflite(self, tflite_model)
        194 output_details = tflite_model.get_output_details()
        195 print(input_details)
        196 tflite_model.set_tensor(
    --> 197     input_details[0]["index"], self.sample_data["sample_data_np"]
        198 )
        199 tflite_model.invoke()
        200 y_pred = tflite_model.get_tensor(output_details[0]["index"])
    
    IndexError: list index out of range
    ```
  - 안드로이드에서 input tensor 이슈가 발생
    ```
    FATAL EXCEPTION: inference
    Process: com.example.tflite_latency_measurement, PID: 32340
    java.lang.IllegalArgumentException: Invalid input Tensor index: 0
     at org.tensorflow.lite.NativeInterpreterWrapper.getInputTensor(NativeInterpreterWrapper.java:381)
     at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:241)
     at org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(InterpreterImpl.java:101)
     at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:77)
     at org.tensorflow.lite.InterpreterImpl.run(InterpreterImpl.java:94)
     at org.tensorflow.lite.Interpreter.run(Interpreter.java:77)
     at com.example.tflite_latency_measurement.MainActivity.modelInference(MainActivity.kt:126)
     at com.example.tflite_latency_measurement.MainActivity.onCreate$lambda$4(MainActivity.kt:69)
     at com.example.tflite_latency_measurement.MainActivity.$r8$lambda$8GwmmyeU7xFwrU8I8YHsZl9Tvbo(Unknown Source:0)
     at com.example.tflite_latency_measurement.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:6)
     at android.os.Handler.handleCallback(Handler.java:942)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loopOnce(Looper.java:201)
     at android.os.Looper.loop(Looper.java:288)
     at android.os.HandlerThread.run(HandlerThread.java:67)
    ```

**Comment by jgpark92** [comment]
1. torch2tflite 변환 검증코드가 작동하지 않음 -> 아래와 같이 수정하면 동작함
    - 마지막 detect layer는 제거함 (search space에 포함되지 않으니)
 
- latency_predictor/arch_utils.py
`class skin_head(nn.Module):
    def __init__(self, arch, save):
        super(skin_head, self).__init__()
        self.model = arch[:-1]
        self.save = save
        self.y = [None for _ in range(27)]
        self.y[12] = torch.rand(1, 512, 80, 80)
        self.y[19] = torch.rand(1, 1024, 40, 40)

    def forward(self, x):
        device = x.get_device()
        if device >= 0:
            device = "cuda:" + str(device)
        else:
            device = "cpu"
        for m in self.model:
            if m.f != -1:  # if not from previous layer
                x = (
                    self.y[m.f].to(device)
                    if isinstance(m.f, int)
                    else [x if j == -1 else self.y[j] for j in m.f]
                )  # from earlier laself.yers
            x = m(x)  # run
            self.y.append(x.detach() if m.i in self.save else None)
        return x`

- torch2tflite.ipynb
dummy_input_shape 부분 수정
`if 'backbone' in name:
        dummy_input_shape = (640, 640, 3)
    else:
        dummy_input_shape = (20, 20, 1024)`
